chore: make devnet Makefile more resillient and informative

diff --git a/integration/test/Makefile b/integration/test/Makefile
--- a/integration/test/Makefile
+++ b/integration/test/Makefile
@@ -1,12 +1,15 @@
 .PHONY: devnet/up devnet/down motionlarity/up motionlarity/down test
 
 ./devnet/.up:
-	echo "Run Boost Devnet from pre-built images"
-	rm -rf ./devnet/data && docker compose -f ./devnet/docker-compose.yaml up -d
-	echo "Await Lotus full node startup"
+	@echo "Running Boost Devnet from pre-built images"
+	@rm -rf ./devnet/data || (echo "\033[1mCould not clean devnet\033[0m, try running 'sudo rm -rf ./devnet/data'" && false)
+	docker compose -f ./devnet/docker-compose.yaml up -d
+	@echo "Awaiting Lotus full node startup..."
 	docker compose -f ./devnet/docker-compose.yaml exec lotus lotus wait-api --timeout=20m
-	echo "Await Lotus-miner full node startup"
+	@echo "Lotus full node started"
+	@echo "Awaiting Lotus-miner full node startup..."
 	docker compose -f ./devnet/docker-compose.yaml exec lotus-miner lotus-miner wait-api --timeout=20m
+	@echo "Lotus-miner full node started"
 	touch ./devnet/.up
 
 devnet/up: ./devnet/.up
@@ -16,7 +19,7 @@ devnet/up: ./devnet/.up
 	touch ./devnet/.boostready
 
 ./motionlarity/.env.local: ./devnet/.up
-	echo "Set up Motion Wallet and API endpoints"
+	@echo "Setting up Motion Wallet and API endpoints"
 	cat ./motionlarity/.env > ./motionlarity/.env.local
 	echo "" >> ./motionlarity/.env.local
 	./integration-setup.sh ./motionlarity/.env.local
@@ -24,12 +27,14 @@ devnet/up: ./devnet/.up
 motionlarity/setup: ./motionlarity/.env.local ./devnet/.boostready
 
 devnet/down: motionlarity/down
-	docker compose -f ./devnet/docker-compose.yaml down && sleep 2 && rm -rf ./devnet/data
-	rm ./devnet/.up || true
+	docker compose -f ./devnet/docker-compose.yaml down
+	sleep 2
+	rm -f ./devnet/.up || true
+	@rm -rf ./devnet/data || (echo "\033[31mCould not clean devnet\033[0m, try running 'sudo rm -rf ./devnet/data'" && false)
 
 ./motionlarity/.up: ./motionlarity/.env.local ./devnet/.boostready
 	./buildsingularity.sh
-	echo "Run Motionlarity"
+	@echo "Runing Motionlarity"
 	docker compose -f ./motionlarity/docker-compose.yaml --env-file ./motionlarity/.env.local up -d
 	./waitmotion.sh
 	touch ./motionlarity/.up
@@ -38,10 +43,10 @@ motionlarity/up: ./motionlarity/.up
 
 motionlarity/down:
 	docker compose -f ./motionlarity/docker-compose.yaml down --rmi=all --volumes
-	rm ./motionlarity/.up || true
-	rm ./motionlarity/.env.local || true
-	rm ./devnet/.boostready || true
+	rm -f ./motionlarity/.up || true
+	rm -f ./motionlarity/.env.local || true
+	rm -f ./devnet/.boostready || true
 
 test: motionlarity/up
-	echo "Run Motion integration tests"
+	@echo "Running Motion integration tests"
 	MOTION_INTEGRATION_TEST='true' go test . -v --count=1
